apiVersion: v1
name: ollama
description: Helm chart used to deploy the Ollama for Kubernetes
home: https://ollama.com/
icon: https://ollama.com/public/ollama.png

version: 0.1.0

maintainers:
    - name: James Flanders
      email: jens.caenen@telenet.be