###############################################################
# Common
###############################################################

# Name of the application
app: "minecraft"

# Tag of the container image(s)
tag: "latest"

###############################################################
# Accessibility
###############################################################

# IP address to use for the LoadBalancer
# ip: "192.168.48.x"

# Port(s) to expose for the container
port: 25565

###############################################################
# Application Configuration
###############################################################

# Minecraft version to host the server on
minecraft_version: "26.1.2"

# Whether to the EULA for the Minecraft
minecraft_eula: true

# Type of the Minecraft server (e.g. PAPER, VANILLA, SPIGOT,...)
minecraft_type: "PAPER"

# Initial memory usage on the Minecraft server
minecraft_init_memory: "2G"

# Maximum memory usage on the Minecraft server
minecraft_max_memory: "4G"

# Maximum number of players allowed on the Minecraft server
minecraft_max_players: 20

# Whether to enable PVP on the Minecraft server
minecraft_pvp: true

# Seed for the initial map generator
# minecraft_seed: ""

# Timezone for the Minecraft server
minecraft_timezone: "Europe/Brussels"

# Whether to enable BlueMap for the Minecraft server (Required BlueMap plugin to work)
minecraft_bluemap_enabled: false

##### The following parameters only apply if 'minecraft_bluemap_enabled' is set to 'true' #####

# Hostname for the BlueMap server
minecraft_bluemap_host: "bluemap.caenen.net"

###############################################################
# Volumes and Storage
###############################################################

##### The following parameters only apply on the first deployment of this instance of the application. #####

# Name of the 'StorageClass' to use for the PersistentVolumeClaim.
storage_class_name: "nfs"

# Size of the PersistentVolumeClaim.
storage_size: "500Mi"