apiVersion: v1
name: wikijs
description: Helm chart used to deploy a WikiJS
home: https://js.wiki/
icon: https://js.wiki/img/wikijs-full-2021.b840e376.svg

version: 0.1.0

maintainers:
    - name: James Flanders
      email: jens.caenen@telenet.be