apiVersion: v1
name: portainer_agent
description: Helm chart used to deploy the Portainer Agent for Kubernetes
home: https://www.portainer.io/
icon: https://cdn.worldvectorlogo.com/logos/portainer.svg

type: application

version: 0.1.0
appVersion: v1.3.0

sources:
    - https://downloads.portainer.io/ee2-32/portainer-agent-k8s-lb.yaml

maintainers:
    - name: James Flanders
      email: jens.caenen@telenet.be