###############################################################
# Common
###############################################################

# Name of the application
app: "portainer-agent"

# Tag of the container image(s)
tag: "2.41.0-alpine"

###############################################################
# Accessibility
###############################################################

# IP address to use for the LoadBalancer
# ip: "192.168.48.x"

# Port(s) to expose for the container
port: 9001