apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wireguard-server-ingress
  annotations:
    app.kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: {{ .Values.host.server }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wireguard-server-service
                port:
                  number: 51820
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wireguard-ui-ingress
  annotations:
    app.kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: {{ .Values.host.ui }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wireguard-ui-service
                port:
                  number: 51821