apiVersion: v1
kind: Service
metadata:
  name: wireguard-server-service
spec:
  type: ClusterIP
  ports:
  - protocol: UDP
    port: 51820
  selector:
    app: wireguard
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-ui-service
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 51821
  selector:
    app: wireguard