apiVersion: v1
name: gramps
description: Helm chart used to deploy a Gramps
home: https://www.grampsweb.org/
icon: https://www.grampsweb.org/logo.svg

version: 0.1.0

maintainers:
    - name: James Flanders
      email: jens.caenen@telenet.be