apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: "ollama/ollama:{{ .Values.tag }}"
          ports:
            - name: http
              containerPort: 11434
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0:11434"
            - name: OLLAMA_KEEP_ALIVE
              value: "2h"
            - name: OLLAMA_CONTEXT_LENGTH
              value: "8192"
            - name: OLLAMA_NUM_PARALLEL
              value: "1"
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "12Gi"
          volumeMounts:
            - name: {{ .Values.app }}-ollama
              mountPath: /root/.ollama
      volumes:
        - name: {{ .Values.app }}-ollama
          persistentVolumeClaim:
            claimName: {{ .Values.app }}-ollama-pvc