apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 11434
      targetPort: 11434
  selector:
    app: {{ .Values.app }}