apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}-worker
  template:
    metadata:
      labels:
        app: {{ .Values.app }}-worker
    spec:
      containers:
        - name: {{ .Values.app }}-worker
          image: "ghcr.io/gramps-project/grampsweb:{{ .Values.tag_worker }}"
          command:
            - celery
            - -A
            - gramps_webapi.celery
            - worker
            - --loglevel=INFO
            - --concurrency=2
          env:
            - name: GRAMPSWEB_TREE
              value: "Caenen"
            - name: GRAMPSWEB_CELERY_CONFIG__broker_url
              value: "redis://{{ .Values.app }}-storage-service:6379/0"
            - name: GRAMPSWEB_CELERY_CONFIG__result_backend
              value: "redis://{{ .Values.app }}-storage-service:6379/0"
            - name: GRAMPSWEB_RATELIMIT_STORAGE_URI
              value: "redis://{{ .Values.app }}-storage-service:6379/1"
          volumeMounts:
            - name: {{ .Values.app }}-app
              mountPath: /app/users
              subPath: users
            - name: {{ .Values.app }}-app
              mountPath: /app/indexdir
              subPath: indexdir
            - name: {{ .Values.app }}-app
              mountPath: /app/thumbnail_cache
              subPath: thumbnail_cache
            - name: {{ .Values.app }}-app
              mountPath: /app/cache
              subPath: cache
            - name: {{ .Values.app }}-app
              mountPath: /app/secret
              subPath: secret
            - name: {{ .Values.app }}-app
              mountPath: /app/media
              subPath: media
            - name: {{ .Values.app }}-app
              mountPath: /app/tmp
              subPath: tmp
            - name: {{ .Values.app }}-grampsdb
              mountPath: /root/.gramps/grampsdb
      volumes:
      - name: {{ .Values.app }}-app
        persistentVolumeClaim:
          claimName: {{ .Values.app }}-app-pvc
      - name: {{ .Values.app }}-grampsdb
        persistentVolumeClaim:
          claimName: {{ .Values.app }}-grampsdb-pvc