###############################################################
# Common
###############################################################

# Name of the application
app: "project-send"

# Versions of the images
tag_application: latest
tag_database: 9.7

###############################################################
# Accessibility
###############################################################

# Name of the DNS record to link to the container.
host: "filetransfer.caenen.net"

# Secret for the MySQL Database
secret_name: "project-send-database-secret"

###############################################################
# Volumes and Storage
###############################################################

##### The following parameters only apply on the first deployment of this instance of the application. #####

# Name of the 'StorageClass' to use for the PersistentVolumeClaim.
storage_class_name: "nfs"

# Size of the PersistentVolumeClaim.
storage_size_application: "500Mi"
storage_size_database: "10Gi"