apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.app }}
        image: "ghcr.io/home-assistant/home-assistant:{{ .Values.tag }}"
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        volumeMounts:
          - name: {{ .Values.app }}-config
            mountPath: /config
      volumes:
        - name: {{ .Values.app }}-config
          persistentVolumeClaim:
            claimName: {{ .Values.app }}-config-pvc