apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app }}-ingress
  annotations:
    app.kubernetes.io/ingress.class: "traefik"
spec:
  tls:
    - hosts:
        - ha.caenen.net
      secretName: {{ .Values.app }}-caenen-net-tls
  rules:
    - host: ha.caenen.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app }}-service
                port:
                  number: 8123