apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service
spec:
  type: NodePort
  ports:
  - name: voice
    protocol: UDP
    port: 9987
    targetPort: 9987
    nodePort: {{ .Values.voice_port }}
  - name: ftp
    protocol: UDP
    port: 30033
    targetPort: 30033
    nodePort: {{ .Values.ftp_port }}
  selector:
    app: {{ .Values.app }}