apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service
  {{- if .Values.ip }}
  annotations:
    metallb.io/loadBalancerIPs: {{ .Values.ip }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    - name: voice
      protocol: UDP
      port: {{ .Values.voice_port }}
      targetPort: 9987
    - name: ftp
      protocol: UDP
      port: {{ .Values.ftp_port }}
      targetPort: 30033
  selector:
    app: {{ .Values.app }}