apiVersion: v1
name: teamspeak6-server
description: Helm chart used to deploy a Teamspeak 6 Server
home: https://teamspeak.com/en/
icon: https://teamspeak.com/user/themes/teamspeak/images/logo_inverse.svg

version: 0.1.5

maintainers:
    - name: James Flanders
      email: jens.caenen@telenet.be