###############################################################
# Common Values
###############################################################

# Name of the application
app: "teamspeak6-server"

# Tag of the container image(s)
tag: "6.0.0-beta9"

###############################################################
# Accessibility
###############################################################

# IP address to use for the LoadBalancer
ip: "192.168.48.13"

# Port(s) to expose for the container
voice_port: 9987
ftp_port: 30033

###############################################################
# Volumes and Storage
###############################################################

##### The following parameters only apply on the first deployment of this instance of the application. #####

# Name of the 'StorageClass' to use for the PersistentVolumeClaim.
storage_class_name: "nfs"

# Size of the PersistentVolumeClaim.
storage_size: "500Mi"