###############################################################
# Common
###############################################################

# Name of the application
app: "slagerij-rob"

# Versions of the images
tag_frontend: 0.1.1
tag_backend: 0.1.5
tag_database: 17.6-alpine

###############################################################
# Accessibility
###############################################################

# Name of the DNS record to link to the container.
host: "slagerij-rob.caenen.net"

# Secret for the PostgreSQL Database
secret_name: "slagerij-rob-database-secret"

###############################################################
# Volumes and Storage
###############################################################

##### The following parameters only apply on the first deployment of this instance of the application. #####

# Name of the 'StorageClass' to use for the PersistentVolumeClaim.
storage_class_name: "nfs"

# Size of the PersistentVolumeClaim.
storage_size: "500Mi"