apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: lscr.io/linuxserver/speedtest-tracker:latest
          env:
            - name: APP_KEY
              value: "base64:h0hu0NV4f8hhxzrWgoNrtbLCcJOGMBD/1TkOe58wv6Y="
            - name: DB_CONNECTION
              value: "sqlite"
            - name: SPEEDTEST_SCHEDULE
              value: "*/15 * * * *"
            - name: APP_TIMEZONE
              value: "Europe/Brussels"
            - name: DISPLAY_TIMEZONE
              value: "Europe/Brussels"
            - name: CHART_DATETIME_FORMAT
              value: "j/m/y G:i"
            - name: DATETIME_FORMAT
              value: "j M Y, G:i:s"
          ports:
            - containerPort: 443
              name: https
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.app }}-config
              mountPath: /config
      volumes:
        - name: {{ .Values.app }}-config
          persistentVolumeClaim:
            claimName: {{ .Values.app }}-config-pvc