{{ if .Values.include_volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
{{ end }}