apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}-application
  template:
    metadata:
      labels:
        app: {{ .Values.app }}-application
    spec:
      containers:
        - name: {{ .Values.app }}-application-pod
          image: "lscr.io/linuxserver/projectsend:{{.Values.tag_application}}"
          ports:
            - containerPort: 80
              name: tcp
              protocol: TCP
          env:
            - name: TZ
              value: "Europe/Brussels"
          volumeMounts:
            - name: {{ .Values.app }}-application
              mountPath: /data
              subPath: data
            - name: {{ .Values.app }}-application
              mountPath: /config
              subPath: config
      volumes:
        - name: {{ .Values.app }}-application
          persistentVolumeClaim:
            claimName: {{ .Values.app }}-application-pvc