###############################################################
# Common Values
###############################################################

# Name of the application
app: "speedtest-tracker"

# Tag of the container image(s)
tag: "1.14.0"

###############################################################
# Accessibility
###############################################################

# Name of the DNS record to link to the container.
host: "speedtest.caenen.net"

###############################################################
# Volumes and Storage
###############################################################

##### The following parameters only apply on the first deployment of this instance of the application. #####

# Name of the 'StorageClass' to use for the PersistentVolumeClaim.
storage_class_name: "nfs"

# Size of the PersistentVolumeClaim.
storage_size: "500Mi"