###############################################################
# Common Values
###############################################################

# Name of the application
app: "speedtest-tracker"

# Tag of the container image(s)
tag_application: 1.14.1
tag_database: 15-alpine

###############################################################
# Accessibility
###############################################################

# Name of the DNS record to link to the container.
host: "speedtest.caenen.net"

# Secret for the application and PostgreSQL Database
application_secret_name: "speedtest-tracker-application-secret"
database_secret_name: "speedtest-tracker-database-secret"

###############################################################
# Volumes and Storage
###############################################################

##### The following parameters only apply on the first deployment of this instance of the application. #####

# Name of the 'StorageClass' to use for the PersistentVolumeClaim.
storage_class_name: "nfs"

# Size of the PersistentVolumeClaim.
storage_size: "1Gi"