###############################################################
# Common Values
###############################################################

# Name of the application
app: "speedtest-tracker"

###############################################################
# Accessibility
###############################################################

# Name of the DNS record to link to the container.
host: "speedtest.caenen.net"

###############################################################
# Volumes and Storage
###############################################################

# Include the creation of the PersistentVolumeClaim
include_volumes: false

##### The following parameters only apply if 'include_volumes' is set to 'true' #####

# Name of the 'StorageClass' to use for the PersistentVolumeClaim.
storage_class_name: "nfs"

# Size of the PersistentVolumeClaim.
storage_size: "500Mi"