apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.app }}-daemonset
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      serviceAccountName: {{ .Values.app }}-sa-clusteradmin
      containers:
      - name: {{ .Values.app }}
        image: portainer/agent:2.27.3
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: DEBUG
        - name: AGENT_CLUSTER_ADDR
          value: "{{ .Values.app }}-headless-service"
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 9001
          protocol: TCP