apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app }}
  ports:
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-headless-service
spec:
  clusterIP: None
  selector:
    app: {{ .Values.app }}