apiVersion: v1
kind: Service
metadata:
  name: portainer-agent-service
  namespace: kube-portainer-agent
spec:
  type: LoadBalancer
  selector:
    app: portainer-agent
  ports:
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: portainer-agent-headless-service
  namespace: kube-portainer-agent
spec:
  clusterIP: None
  selector:
    app: portainer-agent