apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}-application
  template:
    metadata:
      labels:
        app: {{ .Values.app }}-application
    spec:
      containers:
        - name: {{ .Values.app }}-application
          image: "giandonatoinverso/php-dynamic-qr-code:{{ .Values.tag_application }}"
          ports:
            - containerPort: 80
              name: tcp
              protocol: TCP
          env:
            - name: "TYPE"
              value: "docker"
            - name: "QRCODE_GENERATOR"
              value: "internal.qrcode"
            - name: "DATABASE_HOST"
              value: "{{ .Values.app }}-database-service"
            - name: "DATABASE_PORT"
              value: "3306"
            - name: "DATABASE_USER"
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.secret_name }}
            - name: "DATABASE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.secret_name }}
            - name: "DATABASE_NAME"
              value: "qrcode"
            - name: "DATABASE_PREFIX"
              value: ""
            - name: "DATABASE_CHARSET"
              value: "utf8"
          volumeMounts:
            - name: {{ .Values.app }}-saved-qrcode
              mountPath: /var/www/html/saved_qrcode
      volumes:
        - name: {{ .Values.app }}-saved-qrcode
          persistentVolumeClaim:
            claimName: {{ .Values.app }}-saved-qrcode-pvc