apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-saved-qrcode-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage_class_name }}
  resources:
    requests:
      storage: {{ .Values.storage_size_database }}