apiVersion: v1
name: stremio-service
description: Helm chart used to deploy a Stremio Service
home: https://www.stremio.com/
icon: https://downloadr2.apkmirror.com/wp-content/uploads/2025/03/22/67eb1c3707970_com.stremio.one.png

type: application

version: 0.1.0
appVersion: v4.20.16

sources:
    - https://github.com/maximemoreillon/kubernetes-manifests/tree/master/speedtest-tracker

maintainers:
    - name: James Flanders
      email: jens.caenen@telenet.be