###############################################################
# Common Values
###############################################################

# Name of the application
app: "stremio-service"

# Versions of the images
version: v4.20.16

###############################################################
# Accessibility
###############################################################

# Name of the DNS record to link to the container.
host: "stremio.caenen.net"