###############################################################
# Common Values
###############################################################

# Name of the application
app: "stremio-service"

###############################################################
# Accessibility
###############################################################

# Name of the DNS record to link to the container.
host: "stremio.caenen.net"