###############################################################
# Common Values
###############################################################

# Name of the application
app: "minecraft-java-edition"

# Name of the instance of the application.
instance: "hermippe"

# Name of the DNS record to link to the container.
host: "mc.caenen.net"

# Include the creation of the PersistentVolumeClaim
include_volumes: false