apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-server-service
  {{- if .Values.ip }}
  annotations:
    metallb.io/loadBalancerIPs: {{ .Values.ip }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    - name: tcp
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: 25565
    - name: udp
      protocol: UDP
      port: {{ .Values.port }}
      targetPort: 25565
  selector:
    app: {{ .Values.app }}-server