apiVersion: v1
name: wireguard
description: Helm chart used to deploy Wireguard for Kubernetes
home: https://github.com/wg-easy/wg-easy
icon: https://static-00.iconduck.com/assets.00/wireguard-icon-1024x1024-78n6jncy.png

type: application

version: 0.1.1
appVersion: v14.0.0

maintainers:
    - name: James Flanders
      email: jens.caenen@telenet.be