apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.app }}
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880
          name: http
          protocol: TCP
        volumeMounts:
        - name: {{ .Values.app }}-data
          mountPath: /data
      volumes:
      - name: {{ .Values.app }}-data
        persistentVolumeClaim:
          claimName: {{ .Values.app }}-data-pvc