apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodered-ingress
  annotations:
    app.kubernetes.io/ingress.class: "traefik"
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: nodered-caenen-net-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodered-service
                port:
                  number: 1880