{{ if .Values.include_volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage_class_name }}
  resources:
    requests:
      storage: {{ .Values.storage_size }}
{{ end }}
