apiVersion: v1
name: php-dynamic-qr-code
description: Helm chart used to deploy the PHP-Dynamic QR Code for Kubernetes
home: https://github.com/giandonatoinverso/PHP-Dynamic-Qr-code
icon: https://avatars.githubusercontent.com/u/70962472?s=48&v=4

version: 0.1.1

maintainers:
    - name: James Flanders
      email: jens.caenen@telenet.be