{{ if .Values.include_volumes }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-java-edition-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ end }}